# Generated by Django 5.1.1 on 2024-09-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='category/image'),
            preserve_default=False,
        ),
    ]
